services:
    web:
        build:
            context: .
            dockerfile: ./docker/production/nginx/Dockerfile
        restart: unless-stopped
        volumes:
            - laravel-storage-production:/var/www/storage:ro
        networks:
            - laravel-production
        ports:
            - '${NGINX_PORT:-80}:80'
        depends_on:
            php-fpm:
                condition: service_healthy

    php-fpm:
        build:
            context: .
            dockerfile: ./docker/common/php-fpm/Dockerfile
            target: production
        restart: unless-stopped
        volumes:
            - laravel-storage-production:/var/www/storage
        env_file:
            - .env
        networks:
            - laravel-production
        healthcheck:
            test: ['CMD-SHELL', 'php-fpm-healthcheck || exit 1']
            interval: 10s
            timeout: 5s
            retries: 3
        depends_on:
            - mysql

    php-cli:
        build:
            context: .
            dockerfile: ./docker/php-cli/Dockerfile
        tty: true
        stdin_open: true
        env_file:
            - .env
        networks:
            - laravel-production

    mysql:
        image: mysql:8.4
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        command: >
            mysqld
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql-prod-data:/var/lib/mysql
        networks:
            - laravel-production
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:alpine
        restart: unless-stopped
        networks:
            - laravel-production
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 3

networks:
    laravel-production:
        driver: bridge

volumes:
    laravel-storage-production:
    mysql-prod-data:
