services:
    web:
        build:
            context: .
            dockerfile: ./docker/production/nginx/Dockerfile
        restart: unless-stopped
        volumes:
            - laravel-storage-production:/var/www/storage:ro
        networks:
            - laravel-production
        ports:
            - '${NGINX_PORT:-80}:80'
        depends_on:
            php-fpm:
                condition: service_healthy

    php-fpm:
        build:
            context: .
            dockerfile: ./docker/common/php-fpm/Dockerfile
            target: production
        restart: unless-stopped
        volumes:
            - laravel-storage-production:/var/www/storage
        env_file:
            - .env
        networks:
            - laravel-production
        healthcheck:
            test: ['CMD-SHELL', 'php-fpm-healthcheck || exit 1']
            interval: 10s
            timeout: 5s
            retries: 3
        depends_on:
            mariadb:
                condition: service_healthy

    php-cli:
        build:
            context: .
            dockerfile: ./docker/php-cli/Dockerfile
        tty: true
        stdin_open: true
        env_file:
            - .env
        networks:
            - laravel-production

    mariadb:
        image: mariadb:11
        restart: unless-stopped
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-rootpass}'
        volumes:
            - mariadb-data-production:/var/lib/mysql
        networks:
            - laravel-production
        healthcheck:
            test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --silent']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s

    redis:
        image: redis:alpine
        restart: unless-stopped
        networks:
            - laravel-production
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 3

networks:
    laravel-production:
        driver: bridge

volumes:
    laravel-storage-production:
    mariadb-data-production:
