version: '3.8'

services:
  web:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - laravel-storage-production:/var/www/storage:ro
      - laravel-public-assets:/var/www/public/build:ro
    networks:
      - ofertinhas
      - laravel-production
    depends_on:
        - php-fpm
    labels:
      - "traefik.enable=true"

      # HTTP
      - "traefik.http.routers.dnshopcell-http.rule=Host(`dnshopcell.ofertinhas.site`)"
      - "traefik.http.routers.dnshopcell-http.entrypoints=web"
      - "traefik.http.routers.dnshopcell-http.middlewares=redirect-https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"

      # HTTPS + Let's Encrypt
      - "traefik.http.routers.dnshopcell-https.rule=Host(`dnshopcell.ofertinhas.site`)"
      - "traefik.http.routers.dnshopcell-https.entrypoints=websecure"
      - "traefik.http.routers.dnshopcell-https.tls=true"
      - "traefik.http.routers.dnshopcell-https.tls.certresolver=letsencryptresolver"

      # Porta interna do container
      - "traefik.http.services.dnshopcell.loadbalancer.server.port=80"

  php-fpm:
    image: php:8.2-fpm
    restart: unless-stopped
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    command: sh -c "touch /var/www/html/.env && php-fpm"
    env_file:
      - .env
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USERNAME:-laravel}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--max_connections=200"
    ]
    volumes:
      - mysql-data-production:/var/lib/mysql
    networks:
      - laravel-production
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  ofertinhas:
    external: true
  laravel-production:

volumes:
  mysql-data-production:
  laravel-storage-production:
  laravel-public-assets:
